In [3]:
# Assignment for July 30th is to try and create model with all cols - dont delete any col
# observe the feature_importance when you input all cols
# dont forget to do label encoding and scaling on all cols
# take reference from above example

# In fact, change any parameter and see how the accuracy increases or decreases

In [5]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-1.4.2-py3-none-manylinux2010_x86_64.whl (166.7 MB)
     |████████████████████████████████| 166.7 MB 1.4 MB/s eta 0:00:01
Requirement already satisfied: scipy in /home/deathblade287/anaconda3/lib/python3.8/site-packages (from xgboost) (1.6.2)
Requirement already satisfied: numpy in /home/deathblade287/anaconda3/lib/python3.8/site-packages (from xgboost) (1.20.1)
Installing collected packages: xgboost
Successfully installed xgboost-1.4.2

In [92]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from xgboost.sklearn import XGBClassifier
import os

# sklearn stands for scikit learn which is pre-defined ML library in Python

In [93]:
os.chdir(r"/home/deathblade287/Dropbox/ML")

le=LabelEncoder()
scaler=StandardScaler()
xgb1=XGBClassifier()


# LabelEncoding refers to assigning numeric values to categorical variables (for eg male/female , Yes/No, Sun/Mon/../Sat, etc)
# Scaling lets just park for next class

# We will use XGBoost algorithm for this
# Regression is when we have to predict continuous values for eg 1,1.5,1.6,1.7,1.77,...,2,2.1,2.2,2.3,...,5
# Classification is when we have to predict classes - car/bike , male/female , samsung/iphone/microsoft, etc

#In this case of Fraud, we have to create model which will predict whether it is fraud or not fraud

In [94]:
# XGBoost - Xtreme gradient Boosting

In [95]:
# read data from csv

data = pd.read_csv(r"insurance_claims_0723.csv")

# data is a variable in dataframe

In [96]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   object
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   object
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        1000 non-null   object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: float64(2), int64(17), object(21)
memory usage: 312.6+ KB

In [97]:
cols = data.columns
cols

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported', '_c39'],
      dtype='object')

In [98]:
# transform date feature to convert it into day and week
data['incident_date']=pd.to_datetime(data.incident_date)
data["incident_monthdate"] = data.incident_date.dt.day
data["incident_weekday"]=data.incident_date.dt.dayofweek

#data_incident_date=data["incident_date"]
data=data.drop("incident_date",axis=1)

In [99]:
data["incident_monthdate"]

0      25
1      21
2      22
3      10
4      17
       ..
995    22
996    24
997    23
998    26
999    26
Name: incident_monthdate, Length: 1000, dtype: int64

In [100]:
data["incident_weekday"]

0      6
1      2
2      6
3      5
4      1
      ..
995    6
996    5
997    4
998    3
999    3
Name: incident_weekday, Length: 1000, dtype: int64

In [101]:
# splitting 100/200 format into 2 columns - one col with values before / and other col with valiues after /

csl = data["policy_csl"].str.split("/", n = 1, expand = True)
data["lower_csl"]=csl[0]
data["upper_csl"]=csl[1]


# Use "Others" instead of "?" and then use labelencoding

data["collision_type"].replace("?","Others")
data['collision_type']=le.fit_transform(data['collision_type'])

data["property_damage"].replace("?","Others")
data['property_damage']=le.fit_transform(data['property_damage'])

In [102]:
data["collision_type"]

0      3
1      0
2      2
3      1
4      0
      ..
995    1
996    2
997    3
998    2
999    0
Name: collision_type, Length: 1000, dtype: int64

In [103]:
# data.columns
data

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39,incident_monthdate,incident_weekday,lower_csl,upper_csl
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,52080,Saab,92x,2004,Y,NaN,25,6,250,500
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,3510,Mercedes,E400,2007,Y,NaN,21,2,250,500
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,23100,Dodge,RAM,2007,N,NaN,22,6,100,300
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,50720,Chevrolet,Tahoe,2014,Y,NaN,10,5,250,500
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,4550,Accura,RSX,2009,N,NaN,17,1,500,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,38,941851,1991-07-16,OH,500/1000,1000,1310.80,0,431289,...,61040,Honda,Accord,2006,N,NaN,22,6,500,1000
996,285,41,186934,2014-01-05,IL,100/300,1000,1436.79,0,608177,...,72320,Volkswagen,Passat,2015,N,NaN,24,5,100,300
997,130,34,918516,2003-02-17,OH,250/500,500,1383.49,3000000,442797,...,52500,Suburu,Impreza,1996,N,NaN,23,4,250,500
998,458,62,533940,2011-11-18,IL,500/1000,2000,1356.92,5000000,441714,...,36540,Audi,A5,1998,N,NaN,26,3,500,1000
999,456,60,556080,1996-11-11,OH,250/500,1000,766.19,0,612260,...,3680,Mercedes,E400,2007,N,NaN,26,3,250,500

In [122]:
# this is to use labelencoder wherever the cols have categorical data (not numeric data)

data['policy_bind_date']=le.fit_transform(data['policy_bind_date'])
data['vehicle_claim']=le.fit_transform(data['vehicle_claim'])
data['auto_make']=le.fit_transform(data['auto_make'])
data['auto_model']=le.fit_transform(data['auto_model'])
data['policy_state']=le.fit_transform(data['policy_state'])



data['insured_education_level']=le.fit_transform(data['insured_education_level'])
data['insured_occupation']=le.fit_transform(data['insured_occupation'])
data['insured_hobbies']=le.fit_transform(data['insured_hobbies'])
data['insured_relationship']=le.fit_transform(data['insured_relationship'])
data['incident_type']=le.fit_transform(data['incident_type'])
data['incident_severity']=le.fit_transform(data['incident_severity'])
data['authorities_contacted']=le.fit_transform(data['authorities_contacted'])
data['incident_state']=le.fit_transform(data['incident_state'])
data['police_report_available']=le.fit_transform(data['police_report_available'])
data['auto_make']=le.fit_transform(data['auto_make'])
data['auto_model']=le.fit_transform(data['auto_model'])
data['auto_year']=le.fit_transform(data['auto_year'])

In [123]:
# dropping those columns which we think will have NO impact/effect on fraud

data=data.drop("_c39",axis=1)
data=data.drop("policy_csl",axis=1)

# data=data.drop("policy_number",axis=1)
# data=data.drop("policy_bind_date",axis=1)
# data=data.drop("policy_csl",axis=1)
# data=data.drop("insured_zip",axis=1)
# data=data.drop("insured_sex",axis=1)
# data=data.drop("incident_city",axis=1)
# data=data.drop("incident_hour_of_the_day",axis=1)
# data=data.drop("incident_location",axis=1)
# data=data.drop("injury_claim",axis=1)
# data=data.drop("property_claim",axis=1)
# data=data.drop("age",axis=1)
# data=data.drop("policy_state",axis=1)
# data=data.drop("policy_deductable",axis=1)
# data=data.drop("umbrella_limit",axis=1)
# data=data.drop("insured_education_level",axis=1)
# data=data.drop("insured_relationship",axis=1)
# data=data.drop("capital-gains",axis=1)
# data=data.drop("capital-loss",axis=1)
# data=data.drop("incident_type",axis=1)
# data=data.drop("collision_type",axis=1)
# data=data.drop("authorities_contacted",axis=1)
# data=data.drop("incident_state",axis=1)
# data=data.drop("number_of_vehicles_involved",axis=1)
# data=data.drop("property_damage",axis=1)
# data=data.drop("witnesses",axis=1)
# data=data.drop("auto_model",axis=1)
# data=data.drop("auto_year",axis=1)
# data=data.drop("lower_csl",axis=1)
# data=data.drop("upper_csl",axis=1)
# data=data.drop("incident_monthdate",axis=1)

KeyError: "['_c39'] not found in axis"

In [124]:
data

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,incident_monthdate,incident_weekday,lower_csl,upper_csl
0,328,48,521585,940,2,250/500,1000,1406.91,0,466132,...,6510,13020,545,10,1,9,25,6,250,500
1,228,42,342868,635,1,250/500,2000,1197.22,5000000,468176,...,780,780,38,8,12,12,21,2,250,500
2,134,29,687698,413,2,100/300,2000,1413.14,5000000,430632,...,7700,3850,116,4,30,12,22,6,100,300
3,256,41,227811,19,0,250/500,2000,1415.74,6000000,608117,...,6340,6340,521,3,34,19,10,5,250,500
4,228,44,367455,922,0,500/1000,1000,1583.91,6000000,610706,...,1300,650,66,0,31,14,17,1,500,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,38,941851,67,2,500/1000,1000,1310.80,0,431289,...,17440,8720,664,6,6,11,22,6,500,1000
996,285,41,186934,907,0,100/300,1000,1436.79,0,608177,...,18080,18080,714,13,28,20,24,5,100,300
997,130,34,918516,514,2,250/500,500,1383.49,3000000,442797,...,7500,7500,554,11,19,1,23,4,250,500
998,458,62,533940,831,0,500/1000,2000,1356.92,5000000,441714,...,5220,5220,256,1,5,3,26,3,500,1000
999,456,60,556080,283,2,250/500,1000,766.19,0,612260,...,460,920,42,8,12,12,26,3,250,500

In [125]:
y=data['fraud_reported']

# separating the label or y or dependent variable

KeyError: 'fraud_reported'

In [126]:
data=data.drop("fraud_reported",axis=1)

# dropping it from X since y is not captured as different dataframe

KeyError: "['fraud_reported'] not found in axis"

In [127]:
data.describe()
# .describe is used to view/analyze data statistically 

# 1. Identify outliers with the help of mean, std, max - too high or too low
# 2. see if these outliers have a relation with label (fraud or not fraud)
# 3. if they have no relation, which mean that these outliers are not frauds, then we can remove the rows
# to avoid outliers in our data

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,insured_education_level,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,incident_monthdate,incident_weekday
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,...,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,203.954000,38.948000,546238.648000,470.503000,1.01400,1136.000000,1256.406150,1.101000e+06,501214.488000,2.966000,...,0.971000,52761.94000,7433.420000,7399.570000,347.164000,6.546000,19.318000,10.103000,14.995000,3.04700
std,115.113174,9.140287,257063.005276,274.370077,0.83096,611.864673,244.167395,2.297407e+06,71701.610941,1.948497,...,0.810442,26401.53319,4880.951853,4824.726179,209.404851,4.034869,11.136107,6.015861,8.670995,1.97603
min,0.000000,19.000000,100804.000000,0.000000,0.00000,500.000000,433.330000,-1.000000e+06,430104.000000,0.000000,...,0.000000,100.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000
25%,115.750000,32.000000,335980.250000,235.000000,0.00000,500.000000,1089.607500,0.000000e+00,448404.500000,1.000000,...,0.000000,41812.50000,4295.000000,4445.000000,163.750000,3.000000,10.000000,5.000000,7.750000,1.00000
50%,199.500000,38.000000,533135.000000,468.500000,1.00000,1000.000000,1257.200000,0.000000e+00,466445.500000,3.000000,...,1.000000,58055.00000,6775.000000,6750.000000,351.500000,7.000000,20.000000,10.000000,15.000000,3.00000
75%,276.250000,44.000000,759099.750000,707.250000,2.00000,2000.000000,1415.695000,0.000000e+00,603251.000000,5.000000,...,2.000000,70592.50000,11305.000000,10885.000000,523.250000,10.000000,29.000000,15.000000,22.000000,5.00000
max,479.000000,64.000000,999435.000000,950.000000,2.00000,2000.000000,2047.590000,1.000000e+07,620962.000000,6.000000,...,2.000000,114920.00000,21450.000000,23670.000000,725.000000,13.000000,38.000000,20.000000,31.000000,6.00000

In [128]:
data[data["total_claim_amount"]>100000]

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,incident_monthdate,incident_weekday,lower_csl,upper_csl
11,447,61,214618,370,2,100/300,2000,1137.16,0,615561,...,17680,17680,725,1,4,11,15,6,100,300
149,193,41,217938,227,2,250/500,500,847.03,0,438555,...,17280,17280,724,11,19,16,8,6,250,500
163,112,30,346940,496,2,500/1000,1000,1166.54,0,479852,...,10790,21580,719,4,27,2,21,2,500,1000
181,426,54,398102,318,0,500/1000,2000,1097.71,0,605258,...,16800,16800,699,4,27,2,12,0,500,1000
189,128,28,438817,691,2,500/1000,1000,986.53,0,472720,...,18520,18520,691,6,8,12,16,0,500,1000
293,147,34,806081,810,0,500/1000,1000,1275.81,0,472657,...,15540,15540,709,8,24,3,21,2,500,1000
384,254,41,500384,903,0,250/500,2000,1241.04,0,431361,...,18220,18220,686,1,5,19,4,6,250,500
458,347,51,343421,279,2,500/1000,500,1480.79,9000000,432399,...,8630,17260,723,7,36,2,7,2,500,1000
479,317,46,753844,372,1,250/500,1000,1012.78,0,469126,...,19020,19020,697,8,24,4,26,0,250,500
565,392,50,556415,74,2,100/300,2000,1108.97,0,431496,...,16620,16620,718,10,1,7,14,2,100,300
718,259,44,831668,259,2,250/500,2000,1655.79,0,454529,...,16280,16280,716,1,4,7,15,3,250,500
733,149,34,374545,600,1,250/500,500,664.86,0,608963,...,16160,16160,715,4,30,4,4,2,250,500
996,285,41,186934,907,0,100/300,1000,1436.79,0,608177,...,18080,18080,714,13,28,20,24,5,100,300

In [129]:
cols_refined = data.columns
cols_refined

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'incident_monthdate', 'incident_weekday',
       'lower_csl', 'upper_csl'],
      dtype='object')

In [130]:
# we need to apply scaling before splitting into train_test

In [131]:
data = scaler.fit_transform(data)

ValueError: could not convert string to float: '250/500'

In [114]:
data

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,incident_monthdate,incident_weekday,lower_csl,upper_csl
0,328,48,521585,940,OH,250/500,1000,1406.91,0,466132,...,6510,13020,545,10,1,9,25,6,250,500
1,228,42,342868,635,IN,250/500,2000,1197.22,5000000,468176,...,780,780,38,8,12,12,21,2,250,500
2,134,29,687698,413,OH,100/300,2000,1413.14,5000000,430632,...,7700,3850,116,4,30,12,22,6,100,300
3,256,41,227811,19,IL,250/500,2000,1415.74,6000000,608117,...,6340,6340,521,3,34,19,10,5,250,500
4,228,44,367455,922,IL,500/1000,1000,1583.91,6000000,610706,...,1300,650,66,0,31,14,17,1,500,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,38,941851,67,OH,500/1000,1000,1310.80,0,431289,...,17440,8720,664,6,6,11,22,6,500,1000
996,285,41,186934,907,IL,100/300,1000,1436.79,0,608177,...,18080,18080,714,13,28,20,24,5,100,300
997,130,34,918516,514,OH,250/500,500,1383.49,3000000,442797,...,7500,7500,554,11,19,1,23,4,250,500
998,458,62,533940,831,IL,500/1000,2000,1356.92,5000000,441714,...,5220,5220,256,1,5,3,26,3,500,1000
999,456,60,556080,283,OH,250/500,1000,766.19,0,612260,...,460,920,42,8,12,12,26,3,250,500

In [115]:
seed = 9
test_size = 0.3
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=test_size, random_state=seed,stratify=y)

# if we dont use "y" within stratify, the split of our labels (fraud yes/no in our case)
# can be different from ourt train-test size

In [116]:
params = {
    'objective': 'binary:logistic',
    'max_depth': 4,
    'booster':"gbtree",
    'learning_rate': 0.09,
    'n_estimators': 5
}

In [117]:
model_data_xgb_1 = XGBClassifier(**params).fit(X_train, y_train)

# using .fit function means training the algorithm
# it means below
# 1. Start with random theta for all columns
# 2. Calculate cost function
# 3. Update theta
# 4. repeat above steps until the cost function is closer to 0 or stops reducing

/home/deathblade287/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

ValueError: DataFrame.dtypes for data must be int, float, bool or categorical.  When
                categorical type is supplied, DMatrix parameter
                `enable_categorical` must be set to `True`.policy_state, policy_csl, insured_sex, incident_city, incident_location, lower_csl, upper_csl

In [118]:
y_pred_data_xgb_1 = model_data_xgb_1.predict(X_test)

# capturing the predictions of test data
# test data is what algorithm has NOT used for training purpose
# it means that model doesnt know the actual answers but it will predict basis the coefficients model has developed

NameError: name 'model_data_xgb_1' is not defined

In [119]:
print("Accuracy for XGBoost model: %.2f" % (accuracy_score(y_test, y_pred_data_xgb_1) * 100))

# accuracy is calculated by ccmparing actual labels with predicted labels of test data

NameError: name 'y_pred_data_xgb_1' is not defined

In [120]:
print(model_data_xgb_1.feature_importances_)

NameError: name 'model_data_xgb_1' is not defined

In [121]:
import matplotlib.pyplot as plt
plt.bar(cols_refined,model_data_xgb_1.feature_importances_)

NameError: name 'model_data_xgb_1' is not defined

In [ ]:
# we use pickle library to store/save the model
# .pkl file

In [ ]:
# How to use the model in the actual environment
# 1. Store the model (pickle)
# 2. Create an application (for eg website) which takes 12 cols from the customer while he/she logs a claim
# 3. apply the model on 12 cols (.predict)
# 4 finally the outcome is either of the class - fraud or not fraud
# 5. an action can be taken for eg, an email can be sent automatically to the investigation team (insurance company)

In [ ]:
# Next class
# 1. Explain parameters
# 2. Scaling
# 3. deleting rows
# 4. demonstrate complete cycle of applying model
# 5. how to use .describe function


# The standard score of a sample x is calculated as:
# z = (x - u) / s


# where u is the mean of the training samples
# and s is the standard deviation of the training samples

# scaling converts all numbers with mean as 0 and std as 1